### ISSUE TITLE
Sync stops when server gives error 500

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#32]
I am running the plugin in debugger. Had a 500 error today and the sync stopped. Here is the console output:

```
Starting PuDB debugging of plugin ConnectedDrive.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

MyBMWAPIError due to HTTPStatusError: Failed to fetch Vehicle Features.
Unable to get details for vehicle XXXXXXXXXXXXXXXX - (MyBMWAPIError) HTTPStatusError: Failed to fetch Vehicle Features.
Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 76, in raise_for_status_event_handler
    response.raise_for_status()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1733642274844'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 80, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 98, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 220, in do_account_update
    auth_data = await self.get_account_data(cd_account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugin.py", line 208, in get_account_data
    await account.get_vehicles()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 135, in get_vehicles
    raise ex
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 121, in get_vehicles
    await vehicle.get_vehicle_state()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/bimmer_connected/vehicle/vehicle.py", line 108, in get_vehicle_state
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_client.py", line 1814, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_client.py", line 1760, in _send_handling_redirects
    raise exc
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/httpx/_client.py", line 1742, in _send_handling_redirects
    await hook(response)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 78, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive.indigoPlugin/Contents/Packages/bimmer_connected/api/utils.py", line 89, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: Failed to fetch Vehicle Features.
```

**Comment by FlyingDiver** [comment]
That error is deep in the bimmer_connected library.  Best I can do is trap the error and attempt to keep going.

Did the sync resume on it's own or did restarting the plugin resume it?   If not, might need to re-authenticate, in which case I can log that.

**Comment by ryanbuckner** [comment]
Mine stopped running 2 days ago. I had to get a new captcha

**Comment by turribeach** [comment]
The sync didn't resume on it's own nor did restarting the plugin helped. Then I upgraded to Release 2024.0.5 and had to get a new token.

**Comment by FlyingDiver** [comment]
Mine stopped updating about 12 hours ago.  Also needed a new captcha token.

This looks suspiciously like BMW revoked all authorizations at the same time, maybe some kind of system maintenance.

I'll add some exception checking, and maybe a notification event.

**Comment by ryanbuckner** [comment]
Thanks Joe

**Comment by turribeach** [comment]
Yeah I think it might have been a server side issue. I got another error today, 408 Request Timeout:


`Starting PuDB debugging of plugin ConnectedDrive 2.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

MyBMWAPIError due to HTTPStatusError: {"message":"Request Timeout","statusCode":408}
Unable to get details for vehicle XXXXXXXXXXXXXXX - (MyBMWAPIError) HTTPStatusError: {"message":"Request Timeout","statusCode":408}
Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 77, in raise_for_status_event_handler
    response.raise_for_status()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '408 Request Timeout' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1733735042000'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 80, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 98, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 241, in do_account_update
    auth_data = await self.get_account_data(cd_account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugin.py", line 229, in get_account_data
    await account.get_vehicles()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 134, in get_vehicles
    raise ex
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 120, in get_vehicles
    await vehicle.get_vehicle_state()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/vehicle/vehicle.py", line 108, in get_vehicle_state
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1715, in _send_handling_redirects
    raise exc
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1697, in _send_handling_redirects
    await hook(response)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 79, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/utils.py", line 89, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: {"message":"Request Timeout","statusCode":408}`

**Comment by FlyingDiver** [comment]
This appears to have been a server side issue that has been resolved, per issues in the bimmer-connected repository.

**Comment by turribeach** [comment]
Just had another one today:

`Starting PuDB debugging of plugin ConnectedDrive 2.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

MyBMWAPIError due to HTTPStatusError: Failed to fetch Vehicle Features.
Unable to get details for vehicle xxxxxxxxxxxx - (MyBMWAPIError) HTTPStatusError: Failed to fetch Vehicle Features.
Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 77, in raise_for_status_event_handler
    response.raise_for_status()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1733839550000'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 80, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 98, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 241, in do_account_update
    auth_data = await self.get_account_data(cd_account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugin.py", line 229, in get_account_data
    await account.get_vehicles()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 134, in get_vehicles
    raise ex
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 120, in get_vehicles
    await vehicle.get_vehicle_state()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/vehicle/vehicle.py", line 108, in get_vehicle_state
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1715, in _send_handling_redirects
    raise exc
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1697, in _send_handling_redirects
    await hook(response)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 79, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/utils.py", line 89, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: Failed to fetch Vehicle Features.`

**Comment by turribeach** [comment]
Sync stopped after the error. Restarting the plugin did resume syncing. Could you try trapping the error and continiuing the sync?

**Comment by FlyingDiver** [comment]
> Sync stopped after the error. Restarting the plugin did resume syncing. Could you try trapping the error and continiuing the sync?

In progress

**Comment by FlyingDiver** [comment]
New issue for this.  https://github.com/FlyingDiver/Indigo-Connected-Drive/issues/33
