### ISSUE TITLE
Exception stops plugin updating

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Connected-Drive#33]
Just had another one today:

`Starting PuDB debugging of plugin ConnectedDrive 2.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

MyBMWAPIError due to HTTPStatusError: Failed to fetch Vehicle Features.
Unable to get details for vehicle xxxxxxxxxxxx - (MyBMWAPIError) HTTPStatusError: Failed to fetch Vehicle Features.
Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 77, in raise_for_status_event_handler
    response.raise_for_status()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1733839550000'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 80, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 98, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 241, in do_account_update
    auth_data = await self.get_account_data(cd_account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugin.py", line 229, in get_account_data
    await account.get_vehicles()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 134, in get_vehicles
    raise ex
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 120, in get_vehicles
    await vehicle.get_vehicle_state()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/vehicle/vehicle.py", line 108, in get_vehicle_state
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1715, in _send_handling_redirects
    raise exc
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1697, in _send_handling_redirects
    await hook(response)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 79, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/utils.py", line 89, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: Failed to fetch Vehicle Features.`

_Originally posted by @turribeach in https://github.com/FlyingDiver/Indigo-Connected-Drive/issues/32#issuecomment-2537030114_

**Comment by ryanbuckner** [comment]
Me too

**Comment by turribeach** [comment]
> I just committed an update that should trap those errors. I have some more to do before I make an actual release. Feel free to grab the commit and see how it behaves.

Hi, which file is that on? Last commit on plugin.py is from Feb 2024, maybe you forgot to push changes to Github? 

I just had plugin error due to error 500:

`Starting PuDB debugging of plugin ConnectedDrive 2.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

MyBMWAPIError due to HTTPStatusError: Failed to fetch Vehicle Features.
Unable to get details for vehicle XXXXXX - (MyBMWAPIError) HTTPStatusError: Failed to fetch Vehicle Features.
Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 77, in raise_for_status_event_handler
    response.raise_for_status()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1735831027000'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 80, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 98, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 241, in do_account_update
    auth_data = await self.get_account_data(cd_account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugin.py", line 229, in get_account_data
    await account.get_vehicles()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 134, in get_vehicles
    raise ex
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 120, in get_vehicles
    await vehicle.get_vehicle_state()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/vehicle/vehicle.py", line 108, in get_vehicle_state
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1715, in _send_handling_redirects
    raise exc
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1697, in _send_handling_redirects
    await hook(response)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/client.py", line 79, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/api/utils.py", line 89, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: Failed to fetch Vehicle Features.`

**Comment by FlyingDiver** [comment]
It's the last commit in the dev branch.

**Comment by turribeach** [comment]
OK thanks, I taken that code and restarted the plugin. Had another crash today:

`Starting PuDB debugging of plugin ConnectedDrive 2.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "plugin.py", line 257, in get_account_data
    await account.get_vehicles()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/account.py", line 120, in get_vehicles
    await vehicle.get_vehicle_state()
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/bimmer_connected/vehicle/vehicle.py", line 108, in get_vehicle_state
    state_response = await client.get(
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Library/Application Support/Perceptive Automation/Indigo 2024.1/Plugins/ConnectedDrive 2.indigoPlugin/Contents/Packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 81, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 99, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 280, in do_account_update
    auth_data = await self.get_account_data(cd_account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugin.py", line 258, in get_account_data
    except HTTPStatusError as e:
           ^^^^^^^^^^^^^^^
NameError: name 'HTTPStatusError' is not defined

`

**Comment by FlyingDiver** [comment]
You need triple back quotes for a code block.  ;)

**Comment by FlyingDiver** [comment]
Looks like a total failure to contact the BMW servers.  Did this resolve on it's own?  Or with a restart?

**Comment by turribeach** [comment]
> Looks like a total failure to contact the BMW servers. Did this resolve on it's own? Or with a restart?

It needed a full restart.

**Comment by turribeach** [comment]
> You need triple back quotes for a code block. ;)

Thanks, I was wondering why it wouldn't work! I just click on the toolbar icon and it only adds two back quotes, that's silly isn't?

**Comment by FlyingDiver** [comment]
> > You need triple back quotes for a code block. ;)
> 
> Thanks, I was wondering why it wouldn't work! I just click on the toolbar icon and it only adds two back quotes, that's silly isn't?

Those are sufficient for a single line.  I'm not sure what the UI is for a block.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2024.0.6

**Comment by turribeach** [comment]
> Try https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2024.0.6

Thanks! I have installed it and I will report back on issues.

**Comment by FlyingDiver** [comment]
Fixed in pre-release:  https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2025.0.2

**Comment by FlyingDiver** [comment]
Updated release package to remove pre-built packages.

**Comment by turribeach** [comment]
I have now updated to 2025.0.2 but I can confirm 2024.0.6 was rock solid and caught at least dozen exceptions in the ~2 months I tested so I think we can close this issue.
