### ISSUE TITLE
Bug in unit preferences

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Connected-Drive#34]
When choosing the preferred units as miles/gallons in the plugin prefs, mileage, remaining range total, and distance are still returned in km.   Remaining fuel is returned in liters

**Comment by FlyingDiver** [comment]
Not really a bug, I just never got around to implementing the conversions.  The library doesn't have an option to set the units, so I need to look at the units provided and do conversions.

**Comment by FlyingDiver** [comment]
I'm going to remove that setting until I get time to add in the conversions.

**Comment by ryanbuckner** [comment]
I’ll add a request to the library Ryan ***@***.*** Jan 12, 2025, at 12:22 PM, Joe Keenan ***@***.***> wrote:﻿
I'm going to remove that setting until I get time to add in the conversions.

**Comment by FlyingDiver** [comment]
implemented in 2025.0.1

**Comment by FlyingDiver** [comment]
Please test pre-release.

**Comment by ryanbuckner** [comment]
Appears to be working fine within Indigo when I use miles. Indigo Touch still shows km. 
<img width="356" alt="image" src="https://github.com/user-attachments/assets/41ae36c1-a24d-4f8a-bc7d-8c9ed061c165" />
<img width="304" alt="image" src="https://github.com/user-attachments/assets/c71e5d13-6e25-4de6-ab20-e64ae6cda936" />

**Comment by turribeach** [comment]
2025.0.1 doesn't work for me, I get this error:

```
Starting PuDB debugging of plugin ConnectedDrive.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

Exception in thread Thread-1 (run_async_thread):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "plugin.py", line 83, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "plugin.py", line 101, in async_main
    await self.do_account_update(dev_id)
  File "plugin.py", line 372, in do_account_update
    status_ui = state['uiValue']
                ~~~~~^^^^^^^^^^^
KeyError: 'uiValue'
```

**Comment by turribeach** [comment]
I have gone back to 2024.0.6 and I get no errors.

**Comment by ryanbuckner** [comment]
> I have gone back to 2024.0.6 and I get no errors.

It looks like your error is with the UI status you chose in the preferences. I chose door_lock_state and it seems to be ok 

<img width="484" alt="image" src="https://github.com/user-attachments/assets/d95f48c2-0871-4287-a760-a32a88e80794" />

**Comment by ryanbuckner** [comment]
Have you tried changing it and changing it back?

**Comment by FlyingDiver** [comment]
> Appears to be working fine within Indigo when I use miles. Indigo Touch still shows km. 
> 

That's gotta be a caching issue.

**Comment by FlyingDiver** [comment]
> > I have gone back to 2024.0.6 and I get no errors.
> 
> 
> 
> It looks like your error is with the UI status you chose in the preferences. I chose door_lock_state and it seems to be ok 
> 

I forgot to do a uiValue for the door lock state. I'll have to fix that.

**Comment by FlyingDiver** [comment]
Fixed in pre-release:  https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2025.0.2

**Comment by ryanbuckner** [comment]
> Fixed in pre-release: https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2025.0.2

This release won't start for me and I cannot restart it in Interactive Shell. 

EDIT: I was able to get it started by approving it in Privacy Settings and dismissing the warning messages

**Comment by FlyingDiver** [comment]
Oh, I think I forgot to remove the packages so it had extra binaries included,  That probably triggered the error.
